// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatSharpEndToEndTests.Oracle.Flatc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct BasicTypes : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static BasicTypes GetRootAsBasicTypes(ByteBuffer _bb) { return GetRootAsBasicTypes(_bb, new BasicTypes()); }
  public static BasicTypes GetRootAsBasicTypes(ByteBuffer _bb, BasicTypes obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BasicTypes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte Byte { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public ushort UShort { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public short Short { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public bool Bool { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public uint UInt { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public int Int { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public sbyte SByte { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
  public ulong ULong { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public long Long { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public float Float { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public double Double { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public string String { get { int o = __p.__offset(26); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStringBytes() { return __p.__vector_as_span<byte>(26, 1); }
#else
  public ArraySegment<byte>? GetStringBytes() { return __p.__vector_as_arraysegment(26); }
#endif
  public byte[] GetStringArray() { return __p.__vector_as_array<byte>(26); }

  public static Offset<FlatSharpEndToEndTests.Oracle.Flatc.BasicTypes> CreateBasicTypes(FlatBufferBuilder builder,
      byte Byte = 0,
      ushort UShort = 0,
      short Short = 0,
      bool Bool = false,
      uint UInt = 0,
      int Int = 0,
      sbyte SByte = 0,
      ulong ULong = 0,
      long Long = 0,
      float Float = 0.0f,
      double Double = 0.0,
      StringOffset StringOffset = default(StringOffset)) {
    builder.StartTable(12);
    BasicTypes.AddDouble(builder, Double);
    BasicTypes.AddLong(builder, Long);
    BasicTypes.AddULong(builder, ULong);
    BasicTypes.AddString(builder, StringOffset);
    BasicTypes.AddFloat(builder, Float);
    BasicTypes.AddInt(builder, Int);
    BasicTypes.AddUInt(builder, UInt);
    BasicTypes.AddShort(builder, Short);
    BasicTypes.AddUShort(builder, UShort);
    BasicTypes.AddSByte(builder, SByte);
    BasicTypes.AddBool(builder, Bool);
    BasicTypes.AddByte(builder, Byte);
    return BasicTypes.EndBasicTypes(builder);
  }

  public static void StartBasicTypes(FlatBufferBuilder builder) { builder.StartTable(12); }
  public static void AddByte(FlatBufferBuilder builder, byte @byte) { builder.AddByte(0, @byte, 0); }
  public static void AddUShort(FlatBufferBuilder builder, ushort uShort) { builder.AddUshort(1, uShort, 0); }
  public static void AddShort(FlatBufferBuilder builder, short @short) { builder.AddShort(2, @short, 0); }
  public static void AddBool(FlatBufferBuilder builder, bool @bool) { builder.AddBool(3, @bool, false); }
  public static void AddUInt(FlatBufferBuilder builder, uint uInt) { builder.AddUint(4, uInt, 0); }
  public static void AddInt(FlatBufferBuilder builder, int @int) { builder.AddInt(5, @int, 0); }
  public static void AddSByte(FlatBufferBuilder builder, sbyte sByte) { builder.AddSbyte(6, sByte, 0); }
  public static void AddULong(FlatBufferBuilder builder, ulong uLong) { builder.AddUlong(7, uLong, 0); }
  public static void AddLong(FlatBufferBuilder builder, long @long) { builder.AddLong(8, @long, 0); }
  public static void AddFloat(FlatBufferBuilder builder, float @float) { builder.AddFloat(9, @float, 0.0f); }
  public static void AddDouble(FlatBufferBuilder builder, double @double) { builder.AddDouble(10, @double, 0.0); }
  public static void AddString(FlatBufferBuilder builder, StringOffset stringOffset) { builder.AddOffset(11, stringOffset.Value, 0); }
  public static Offset<FlatSharpEndToEndTests.Oracle.Flatc.BasicTypes> EndBasicTypes(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatSharpEndToEndTests.Oracle.Flatc.BasicTypes>(o);
  }
  public BasicTypesT UnPack() {
    var _o = new BasicTypesT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(BasicTypesT _o) {
    _o.Byte = this.Byte;
    _o.UShort = this.UShort;
    _o.Short = this.Short;
    _o.Bool = this.Bool;
    _o.UInt = this.UInt;
    _o.Int = this.Int;
    _o.SByte = this.SByte;
    _o.ULong = this.ULong;
    _o.Long = this.Long;
    _o.Float = this.Float;
    _o.Double = this.Double;
    _o.String = this.String;
  }
  public static Offset<FlatSharpEndToEndTests.Oracle.Flatc.BasicTypes> Pack(FlatBufferBuilder builder, BasicTypesT _o) {
    if (_o == null) return default(Offset<FlatSharpEndToEndTests.Oracle.Flatc.BasicTypes>);
    var _String = _o.String == null ? default(StringOffset) : builder.CreateString(_o.String);
    return CreateBasicTypes(
      builder,
      _o.Byte,
      _o.UShort,
      _o.Short,
      _o.Bool,
      _o.UInt,
      _o.Int,
      _o.SByte,
      _o.ULong,
      _o.Long,
      _o.Float,
      _o.Double,
      _String);
  }
}

public class BasicTypesT
{
  public byte Byte { get; set; }
  public ushort UShort { get; set; }
  public short Short { get; set; }
  public bool Bool { get; set; }
  public uint UInt { get; set; }
  public int Int { get; set; }
  public sbyte SByte { get; set; }
  public ulong ULong { get; set; }
  public long Long { get; set; }
  public float Float { get; set; }
  public double Double { get; set; }
  public string String { get; set; }

  public BasicTypesT() {
    this.Byte = 0;
    this.UShort = 0;
    this.Short = 0;
    this.Bool = false;
    this.UInt = 0;
    this.Int = 0;
    this.SByte = 0;
    this.ULong = 0;
    this.Long = 0;
    this.Float = 0.0f;
    this.Double = 0.0;
    this.String = null;
  }
}


static public class BasicTypesVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Byte*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*UShort*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 8 /*Short*/, 2 /*short*/, 2, false)
      && verifier.VerifyField(tablePos, 10 /*Bool*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 12 /*UInt*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*Int*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*SByte*/, 1 /*sbyte*/, 1, false)
      && verifier.VerifyField(tablePos, 18 /*ULong*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 20 /*Long*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 22 /*Float*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 24 /*Double*/, 8 /*double*/, 8, false)
      && verifier.VerifyString(tablePos, 26 /*String*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
