// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatSharpEndToEndTests.Oracle.Flatc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LocationHolder : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static LocationHolder GetRootAsLocationHolder(ByteBuffer _bb) { return GetRootAsLocationHolder(_bb, new LocationHolder()); }
  public static LocationHolder GetRootAsLocationHolder(ByteBuffer _bb, LocationHolder obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LocationHolder __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatSharpEndToEndTests.Oracle.Flatc.Location? SingleLocation { get { int o = __p.__offset(4); return o != 0 ? (FlatSharpEndToEndTests.Oracle.Flatc.Location?)(new FlatSharpEndToEndTests.Oracle.Flatc.Location()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public string Fake { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFakeBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetFakeBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetFakeArray() { return __p.__vector_as_array<byte>(6); }
  public FlatSharpEndToEndTests.Oracle.Flatc.Location? LocationVector(int j) { int o = __p.__offset(8); return o != 0 ? (FlatSharpEndToEndTests.Oracle.Flatc.Location?)(new FlatSharpEndToEndTests.Oracle.Flatc.Location()).__assign(__p.__vector(o) + j * 12, __p.bb) : null; }
  public int LocationVectorLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FlatSharpEndToEndTests.Oracle.Flatc.LocationHolder> CreateLocationHolder(FlatBufferBuilder builder,
      FlatSharpEndToEndTests.Oracle.Flatc.LocationT SingleLocation = null,
      StringOffset FakeOffset = default(StringOffset),
      VectorOffset LocationVectorOffset = default(VectorOffset)) {
    builder.StartTable(3);
    LocationHolder.AddLocationVector(builder, LocationVectorOffset);
    LocationHolder.AddFake(builder, FakeOffset);
    LocationHolder.AddSingleLocation(builder, FlatSharpEndToEndTests.Oracle.Flatc.Location.Pack(builder, SingleLocation));
    return LocationHolder.EndLocationHolder(builder);
  }

  public static void StartLocationHolder(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddSingleLocation(FlatBufferBuilder builder, Offset<FlatSharpEndToEndTests.Oracle.Flatc.Location> singleLocationOffset) { builder.AddStruct(0, singleLocationOffset.Value, 0); }
  public static void AddFake(FlatBufferBuilder builder, StringOffset fakeOffset) { builder.AddOffset(1, fakeOffset.Value, 0); }
  public static void AddLocationVector(FlatBufferBuilder builder, VectorOffset locationVectorOffset) { builder.AddOffset(2, locationVectorOffset.Value, 0); }
  public static void StartLocationVectorVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(12, numElems, 4); }
  public static Offset<FlatSharpEndToEndTests.Oracle.Flatc.LocationHolder> EndLocationHolder(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatSharpEndToEndTests.Oracle.Flatc.LocationHolder>(o);
  }
  public LocationHolderT UnPack() {
    var _o = new LocationHolderT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(LocationHolderT _o) {
    _o.SingleLocation = this.SingleLocation.HasValue ? this.SingleLocation.Value.UnPack() : null;
    _o.Fake = this.Fake;
    _o.LocationVector = new List<FlatSharpEndToEndTests.Oracle.Flatc.LocationT>();
    for (var _j = 0; _j < this.LocationVectorLength; ++_j) {_o.LocationVector.Add(this.LocationVector(_j).HasValue ? this.LocationVector(_j).Value.UnPack() : null);}
  }
  public static Offset<FlatSharpEndToEndTests.Oracle.Flatc.LocationHolder> Pack(FlatBufferBuilder builder, LocationHolderT _o) {
    if (_o == null) return default(Offset<FlatSharpEndToEndTests.Oracle.Flatc.LocationHolder>);
    var _Fake = _o.Fake == null ? default(StringOffset) : builder.CreateString(_o.Fake);
    var _LocationVector = default(VectorOffset);
    if (_o.LocationVector != null) {
      StartLocationVectorVector(builder, _o.LocationVector.Count);
      for (var _j = _o.LocationVector.Count - 1; _j >= 0; --_j) { FlatSharpEndToEndTests.Oracle.Flatc.Location.Pack(builder, _o.LocationVector[_j]); }
      _LocationVector = builder.EndVector();
    }
    return CreateLocationHolder(
      builder,
      _o.SingleLocation,
      _Fake,
      _LocationVector);
  }
}

public class LocationHolderT
{
  public FlatSharpEndToEndTests.Oracle.Flatc.LocationT SingleLocation { get; set; }
  public string Fake { get; set; }
  public List<FlatSharpEndToEndTests.Oracle.Flatc.LocationT> LocationVector { get; set; }

  public LocationHolderT() {
    this.SingleLocation = new FlatSharpEndToEndTests.Oracle.Flatc.LocationT();
    this.Fake = null;
    this.LocationVector = null;
  }
}


static public class LocationHolderVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SingleLocation*/, 12 /*FlatSharpEndToEndTests.Oracle.Flatc.Location*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Fake*/, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*LocationVector*/, 12 /*FlatSharpEndToEndTests.Oracle.Flatc.Location*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
