// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatSharpEndToEndTests.Oracle.Flatc
{

public enum MyEnum : sbyte
{
  A = 0,
  B = 1,
};


}
