// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatSharpEndToEndTests.Oracle.Flatc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct OuterStruct : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public OuterStruct __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatSharpEndToEndTests.Oracle.Flatc.InnerStruct Inner { get { return (new FlatSharpEndToEndTests.Oracle.Flatc.InnerStruct()).__assign(__p.bb_pos + 0, __p.bb); } }
  public int A { get { return __p.bb.GetInt(__p.bb_pos + 4); } }

  public static Offset<FlatSharpEndToEndTests.Oracle.Flatc.OuterStruct> CreateOuterStruct(FlatBufferBuilder builder, int Inner_A, int A) {
    builder.Prep(4, 8);
    builder.PutInt(A);
    builder.Prep(4, 4);
    builder.PutInt(Inner_A);
    return new Offset<FlatSharpEndToEndTests.Oracle.Flatc.OuterStruct>(builder.Offset);
  }
  public OuterStructT UnPack() {
    var _o = new OuterStructT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(OuterStructT _o) {
    _o.Inner = this.Inner.UnPack();
    _o.A = this.A;
  }
  public static Offset<FlatSharpEndToEndTests.Oracle.Flatc.OuterStruct> Pack(FlatBufferBuilder builder, OuterStructT _o) {
    if (_o == null) return default(Offset<FlatSharpEndToEndTests.Oracle.Flatc.OuterStruct>);
    var _Inner_A = _o.Inner.A;
    return CreateOuterStruct(
      builder,
      _Inner_A,
      _o.A);
  }
}

public class OuterStructT
{
  public FlatSharpEndToEndTests.Oracle.Flatc.InnerStructT Inner { get; set; }
  public int A { get; set; }

  public OuterStructT() {
    this.Inner = new FlatSharpEndToEndTests.Oracle.Flatc.InnerStructT();
    this.A = 0;
  }
}


}
