// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatSharpEndToEndTests.Oracle.Flatc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StructVectorsTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_22_10_26(); }
  public static StructVectorsTable GetRootAsStructVectorsTable(ByteBuffer _bb) { return GetRootAsStructVectorsTable(_bb, new StructVectorsTable()); }
  public static StructVectorsTable GetRootAsStructVectorsTable(ByteBuffer _bb, StructVectorsTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StructVectorsTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatSharpEndToEndTests.Oracle.Flatc.StructVectors? Vec { get { int o = __p.__offset(4); return o != 0 ? (FlatSharpEndToEndTests.Oracle.Flatc.StructVectors?)(new FlatSharpEndToEndTests.Oracle.Flatc.StructVectors()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartStructVectorsTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddVec(FlatBufferBuilder builder, Offset<FlatSharpEndToEndTests.Oracle.Flatc.StructVectors> VecOffset) { builder.AddStruct(0, VecOffset.Value, 0); }
  public static Offset<FlatSharpEndToEndTests.Oracle.Flatc.StructVectorsTable> EndStructVectorsTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatSharpEndToEndTests.Oracle.Flatc.StructVectorsTable>(o);
  }
  public StructVectorsTableT UnPack() {
    var _o = new StructVectorsTableT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(StructVectorsTableT _o) {
    _o.Vec = this.Vec.HasValue ? this.Vec.Value.UnPack() : null;
  }
  public static Offset<FlatSharpEndToEndTests.Oracle.Flatc.StructVectorsTable> Pack(FlatBufferBuilder builder, StructVectorsTableT _o) {
    if (_o == null) return default(Offset<FlatSharpEndToEndTests.Oracle.Flatc.StructVectorsTable>);
    StartStructVectorsTable(builder);
    AddVec(builder, FlatSharpEndToEndTests.Oracle.Flatc.StructVectors.Pack(builder, _o.Vec));
    return EndStructVectorsTable(builder);
  }
}

public class StructVectorsTableT
{
  public FlatSharpEndToEndTests.Oracle.Flatc.StructVectorsT Vec { get; set; }

  public StructVectorsTableT() {
    this.Vec = new FlatSharpEndToEndTests.Oracle.Flatc.StructVectorsT();
  }
}


}
