// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatSharpEndToEndTests.Oracle.Flatc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UnionTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static UnionTable GetRootAsUnionTable(ByteBuffer _bb) { return GetRootAsUnionTable(_bb, new UnionTable()); }
  public static UnionTable GetRootAsUnionTable(ByteBuffer _bb, UnionTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UnionTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatSharpEndToEndTests.Oracle.Flatc.Union ValueType { get { int o = __p.__offset(4); return o != 0 ? (FlatSharpEndToEndTests.Oracle.Flatc.Union)__p.bb.Get(o + __p.bb_pos) : FlatSharpEndToEndTests.Oracle.Flatc.Union.NONE; } }
  public TTable? Value<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public string ValueAsString() { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; }
  public FlatSharpEndToEndTests.Oracle.Flatc.BasicTypes ValueAsBasicTypes() { return Value<FlatSharpEndToEndTests.Oracle.Flatc.BasicTypes>().Value; }
  public FlatSharpEndToEndTests.Oracle.Flatc.Location ValueAsLocation() { return Value<FlatSharpEndToEndTests.Oracle.Flatc.Location>().Value; }
  public string ValueAsstringValue() { return ValueAsString(); }

  public static Offset<FlatSharpEndToEndTests.Oracle.Flatc.UnionTable> CreateUnionTable(FlatBufferBuilder builder,
      FlatSharpEndToEndTests.Oracle.Flatc.Union Value_type = FlatSharpEndToEndTests.Oracle.Flatc.Union.NONE,
      int ValueOffset = 0) {
    builder.StartTable(2);
    UnionTable.AddValue(builder, ValueOffset);
    UnionTable.AddValueType(builder, Value_type);
    return UnionTable.EndUnionTable(builder);
  }

  public static void StartUnionTable(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddValueType(FlatBufferBuilder builder, FlatSharpEndToEndTests.Oracle.Flatc.Union valueType) { builder.AddByte(0, (byte)valueType, 0); }
  public static void AddValue(FlatBufferBuilder builder, int valueOffset) { builder.AddOffset(1, valueOffset, 0); }
  public static Offset<FlatSharpEndToEndTests.Oracle.Flatc.UnionTable> EndUnionTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatSharpEndToEndTests.Oracle.Flatc.UnionTable>(o);
  }
  public UnionTableT UnPack() {
    var _o = new UnionTableT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(UnionTableT _o) {
    _o.Value = new FlatSharpEndToEndTests.Oracle.Flatc.UnionUnion();
    _o.Value.Type = this.ValueType;
    switch (this.ValueType) {
      default: break;
      case FlatSharpEndToEndTests.Oracle.Flatc.Union.BasicTypes:
        _o.Value.Value = this.Value<FlatSharpEndToEndTests.Oracle.Flatc.BasicTypes>().HasValue ? this.Value<FlatSharpEndToEndTests.Oracle.Flatc.BasicTypes>().Value.UnPack() : null;
        break;
      case FlatSharpEndToEndTests.Oracle.Flatc.Union.Location:
        _o.Value.Value = this.Value<FlatSharpEndToEndTests.Oracle.Flatc.Location>().HasValue ? this.Value<FlatSharpEndToEndTests.Oracle.Flatc.Location>().Value.UnPack() : null;
        break;
      case FlatSharpEndToEndTests.Oracle.Flatc.Union.stringValue:
        _o.Value.Value = this.ValueAsString();
        break;
    }
  }
  public static Offset<FlatSharpEndToEndTests.Oracle.Flatc.UnionTable> Pack(FlatBufferBuilder builder, UnionTableT _o) {
    if (_o == null) return default(Offset<FlatSharpEndToEndTests.Oracle.Flatc.UnionTable>);
    var _Value_type = _o.Value == null ? FlatSharpEndToEndTests.Oracle.Flatc.Union.NONE : _o.Value.Type;
    var _Value = _o.Value == null ? 0 : FlatSharpEndToEndTests.Oracle.Flatc.UnionUnion.Pack(builder, _o.Value);
    return CreateUnionTable(
      builder,
      _Value_type,
      _Value);
  }
}

public class UnionTableT
{
  public FlatSharpEndToEndTests.Oracle.Flatc.UnionUnion Value { get; set; }

  public UnionTableT() {
    this.Value = null;
  }
}


static public class UnionTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ValueType*/, 1 /*FlatSharpEndToEndTests.Oracle.Flatc.Union*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Value*/, FlatSharpEndToEndTests.Oracle.Flatc.UnionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
