name: NativeAot Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    env:
      AppVeyorBuild: true
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      working-directory: src
      run: dotnet restore
      
    - name: Build FlatSharp.Compiler
      working-directory: src/FlatSharp.Compiler
      run: dotnet build -c Release
      
    - name: Run FlatSharp.Compiler
      # You may pin to the exact commit or the version.
      # uses: Amadevus/pwsh-script@97a8b211a5922816aa8a69ced41fa32f23477186
      uses: Amadevus/pwsh-script@v2.0.3
      with:
        # PowerShell script to execute in Actions-hydrated context
        script: |
          $fbs = (gci -r src/Tests/CompileTests/NativeAot/*.fbs) -join ";"
          dotnet src/FlatSharp.Compiler/bin/Release/net8.0/FlatSharp.Compiler.dll --nullable-warnings false --normalize-field-names true --input "$fbs" -o src/Tests/CompileTests/NativeAot
          
    - name: Build
      working-directory: src/Tests/CompileTests/NativeAot
      run: dotnet publish -c Release -r win-x64 -f net8.0

    - name: Run
      working-directory: src/Tests/CompileTests/NativeAot/bin/Release/net8.0/win-x64/publish
      run: NativeAot
      
    - name: Upload Files
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: generated-csharp
        path: src/Tests/CompileTests/NativeAot/bin/**/*.*
